name: simulation
channels:
  - conda-forge
dependencies:
  - python==3.8.3
  - imbalanced-learn==0.8.1
  - matplotlib==3.2.2
  - numpy==1.19.5
  - pandas==1.3.5
  - scikit-learn==1.0.0
  - seaborn==0.11.1
  - xgboost==1.3.3
  